name: build-recipe-index
on:
  push:
    branches:
      - recipe-updates
jobs:
  index-recipe-and-merge:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: x64
    - run: pip install xmlschema
    - run: python scripts/python_scripts/build-index-workflow.py
    - run: git merge 'master'
    - uses: actions/checkout@v2
      with:
        repository: 'master'
        token: ${{ github.token }}
    - run: git merge 'recipe-updates'


