# Github workflow action

# files to be updated as recipes change include
# sitemap.xml
# search_index.json
# recipe.html files when the source xml sourece recipe file is changed
# recipe-all.html when there is a change to recipe.xml file
# 
# After a Push it scans for changes and updates files as necessary


name: build-recipe-index
on:
  push:
    paths:
      - 'recipes/xml/*'
  workflow_dispatch:  # This allows manual triggering

jobs:
  check:
    name: Check changed files
    outputs:
      files_modified_or_added: ${{ steps.check_files.outputs.files_modified_or_added }}  # List of changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 2

      - name: check files
        id: check_files
        run: |
          echo "=============== list changed files ==============="
          git diff --name-status HEAD^ HEAD > files.txt

          # Initialize the output
          files_modified_or_added=""

          echo "========== check paths and status of changed files =========="
          while IFS= read -r file
          do
            status=$(echo $file | cut -f1)
            file_name=$(echo $file | cut -f2)
            
            if [[ $file_name == "recipes/xml/"* && ( $status == "A" || $status == "M" ) ]]; then
              echo "File $file_name was added or modified."
              files_modified_or_added="$files_modified_or_added $file_name"
            fi
          done < files.txt

          echo "files_modified_or_added=$files_modified_or_added" >> $GITHUB_OUTPUT

  job_for_recipes:
    name: Job for recipes
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: index recipes
        uses: actions/setup-python@main
        with:
          python-version: '3.x'
          architecture: x64

      - name: install_dependencies
        run: pip install xmlschema lxml BeautifulSoup4

      - name: generate html files for changed recipes
      # only generate the html recipes for the changes xml files
        if: needs.check.outputs.files_modified_or_added != ''
        run: |
          python scripts/python_scripts/make-recipe-pages.py ${{ needs.check.outputs.files_modified_or_added }}

      # always regenerate the site index to capture adds, modifications, and deletes
      - name: generate sitemap and search index files
        run: python scripts/python_scripts/build-index-workflow.py
      
      # always regenerate the recipe-all html to capture adds, modifications, and deletes
      - name: generate html for all recipes
        run: python scripts/python_scripts/make-recipe-all-page.py

      - if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add search_index.json
          git add sitemap.xml
          git add recipe-all.html
          git add recipes/html/*.html

          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "automated html and index update"
            git push
