# Github workflow action

# files to be updated as recipes change include
# sitemap.xml
# search_index.json
# recipe.html files when the source xml sourece recipe file is changed
# recipe-all.html when there is a change to recipe.xml file
# 
# After a Push it scans for changes and updates files as necessary


name: build-recipe-index
on:
  push:
    paths:
      - 'recipes/xml/*'
  workflow_dispatch:  # This allows manual triggering

jobs:
  check:
    name: Check changed files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 2

      - name: check files
        id: check_files
        run: |
          echo "=============== list changed files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of changed files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != "recipes/xml/"* ]]; then
              echo "This file is not under the directory 'recipes/xml/'."
              # echo "::set-output name=run_job::false"
              echo "run_job=false" >> $GITHUB_OUTPUT
              break
            else
              echo "this file is in RECIPE/XML/ directory."
              # echo "::set-output name=run_job::true"
              echo "run_job=true" >> $GITHUB_OUTPUT
            fi
          done < files.txt

  job_for_recipes:
    name: Job for recipes
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: index recipes
        uses: actions/setup-python@main
        with:
          python-version: '3.x'
          architecture: x64

      - name: install_dependencies
        run: pip install xmlschema lxml BeautifulSoup4

      - name: generate sitemap and search index files
        run: python scripts/python_scripts/build-index-workflow.py

      - name: generate html files for changed recipes and recipes-all
        run: |
          python scripts/python_scripts/make-recipe-pages.py
          python scripts/python_scripts/make-recipe-all-page.py

      - if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add search_index.json
          git add sitemap.xml
          git add recipe-all.html
          git add recipes/html/*.html

          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "automated html and index update"
            git push
          fi