# Github workflow action

# After push it scans for canges and updates recipelist and sitemap


name: build-recipe-index
on: 
  push:


jobs:
  check:
    name: Check changed files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 2

      - name: check files
        id: check_files
        run: |
          echo "=============== list changed files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of changed files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != "recipes"* ]]; then
              echo "This file is not under the directory 'recipes'."
              # echo "::set-output name=run_job::false"
              echo "run_job=false" >> $GITHUB_OUTPUT
              break
            else
              echo "this file is in RECIPE directory."
              # echo "::set-output name=run_job::true"
              echo "run_job=true" >> $GITHUB_OUTPUT
            fi
          done < files.txt

  job_for_recipes:
    name: Job for recipes
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: index recipes
        uses: actions/setup-python@main
        with:
          python-version: '3.x'
          architecture: x64
      - run: pip install xmlschema
#      - run: python scripts/update-recipeindex.py
      - run: python scripts/python_scripts/build-index-workflow.py
      - if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: git add xml/recipeList.xml
      - run: git add sitemap.xml
      - run: git commit -m "automated recipe index update"
      - run: git push