# name: build-recipe-index
# on: 
#   push:
# 
# on:
#   push:
#     branches:
#       - recipe-updates
# jobs:
#   index-recipe-and-merge:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           token: ${{ github.token }}
#       - uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'
#           architecture: x64
#       - run: pip install xmlschema
#       - run: python scripts/update-index-work.py
#       - if: ${{ success() }}
#         run: |
#           git config user.name github-actions
#           git config user.email github-actions@github.com
#       - run: git status
#       - run: git add .
#       - run: git commit -m "automated recipe and index update"
#       - run: git push




name: build-recipe-index
on: 
  push:


jobs:
  check:
    name: Check changed files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check files
        id: check_files
        run: |
          echo "=============== list changed files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of changed files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != "recipes"* ]]; then
              echo "This file is not under the directory 'recipes'."
              echo "::set-output name=run_job::false"
              break
            else
              echo "::set-output name=run_job::true"
            fi
          done < files.txt

  job_for_recipes:
    name: Job for recipes
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: run for recipes
        run: echo "Updates made to recipes"
