name: build-recipe-index
on: [push]
jobs:
  index-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: x64
    -run: python scripts/python_scripts/build-index.py
