name: build-recipe-index
on:
  push:
    branches:
      - recipe-updates
jobs:
  - name: index-files-and-merge
    runs-on: ubuntu-latest
    steps:
    - name: validate recipe and update index
      uses: actions/checkout@v2
      uses: actions/setup-python@v2

      run: pip install xmlschema
        with:
          python-version: '3.x'
          architecture: x64
          cache: 'pip'
      run: python scripts/python_scripts/build-index-workflow.py
        with:
          python-version: '3.x'
          architecture: x64
          cache: 'pip'
    - name: merge master to recipe-update
      run: git merge 'master'
    - name: merge branck back to master
      uses: actions/checkout@v2
      with:
        repository: 'master'
        token: ${{ github.token }}
      run: git merge 'recipe-updates'


